#!/usr/bin/env ruby

dir = File.dirname(__FILE__)
require "#{dir}/../config/environment"

http_server = Http::Server.new(:port => 9090)
xmpp_dispatcher = Xmpp::Dispatcher.new

trap "INT" do
  http_server.stop
  xmpp_dispatcher.stop
  exit
end

http_thread = Thread.new do
  http_server.start
end

xmpp_thread = Thread.new do
  xmpp_dispatcher.start
end

xmpp_thread.join
http_thread.join