source 'http://rubygems.org'

gem 'rails', '3.0.4'
gem 'pg', '0.9.0'
gem 'sequel', '3.16.0'
gem 'sequel_rails3'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'rgl', :require => ['rgl/base', 'rgl/adjacency', 'rgl/topsort']
gem 'erector'
gem 'pony'

# monarch
gem 'guid'
gem 'json'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rr'
  gem 'machinist'
  gem 'faker'
end