//= require "views/login"
//= require "views/signup"
//= require "views/organizations"
//= require "views/elections"
//= require "views/candidates"
//= require "views/candidate"
//= require "views/rankings"
//= require "views/error_list"