//= require "views/login"
//= require "views/signup"
//= require "views/organization"
//= require "views/elections"
//= require "views/candidates"
//= require "views/ranking"
//= require "views/error_list"