dir = File.dirname(__FILE__)
require "#{dir}/models/record"
require "#{dir}/models/exposed_repository"
require "#{dir}/models/user"
require "#{dir}/models/organization"
require "#{dir}/models/membership"
require "#{dir}/models/election"
require "#{dir}/models/candidate"
require "#{dir}/models/ranking"
require "#{dir}/models/vote"
require "#{dir}/models/majority"
require "#{dir}/models/invitation"
require "#{dir}/models/subscription_manager"
