dir = File.dirname(__FILE__)
require "#{dir}/views/layout"
require "#{dir}/views/floating_card"
require "#{dir}/views/redirect_to_login"
require "#{dir}/views/no_internet_explorer"
require "#{dir}/views/app"
require "#{dir}/views/home"
require "#{dir}/views/learn_more"
require "#{dir}/views/signup"
require "#{dir}/views/login"
require "#{dir}/views/request_password_reset"
require "#{dir}/views/sent_password_reset_token"
require "#{dir}/views/reset_password"