#!/usr/bin/env ruby
require "pathname"
dir = Pathname.new(File.expand_path(File.dirname(__FILE__))).realpath

puts "Starting app server"

server_path = "#{dir}/../../script/server 2>&1"

if File.exist?("/opt/local/bin/ruby")
  exec "/opt/local/bin/ruby #{server_path}"
else
  exec server_path
end

